import BackToTop from "@/components/BackToTopButton.jsx";
import "@/styles/globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"], // choose the weights you need
  display: "swap",
});

export const metadata = {
  title: "Solar/Electrical Online Store",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="scrollbar-thin scrollbar-thumb-sky-500 hover:scrollbar-thumb-sky-400 active:scrollbar-thumb-sky-300 scrollbar-track-slate-100 self-dark:scrollbar-track-slate-900"
    >
      <head>
        <meta name="theme-color" content="#601c1c" />
      </head>
      <body
        id="app"
        className={`${montserrat.className} antialiased text-base lg:text-lg`}
      >
        {children}
        <BackToTop />
      </body>
    </html>
  );
}
