import "@/styles/globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"], // choose the weights you need
  display: "swap",
});

export const metadata = {
  title: "Solar/Electrical Online Store",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#601c1c" />
      </head>
      <body
        className={`${montserrat.className} antialiased text-base lg:text-lg`}
      >
        {children}
      </body>
    </html>
  );
}
