const ProductsList = [
  {
    id: "ch-c-001",
    title: "40A MPPT Solar Charge Controller with Monitoring",
    imageUrl: "/imgs/me34.jpg",
    price: 20000,
    currency: "XAF",
    category: "Charge Controller",
  },
  {
    id: "ch-c-002",
    title: "60A PWM Solar Charge Controller",
    imageUrl: "/imgs/me34.jpg",
    price: 25000,
    currency: "XAF",
    category: "Charge Controller",
  },
  {
    id: "sp-001",
    title: "150W Polycrystalline Solar Panel",
    imageUrl: "/imgs/me34.jpg",
    price: 35000,
    currency: "XAF",
    category: "Solar Panel",
  },
  {
    id: "sp-002",
    title: "250W Monocrystalline Solar Panel",
    imageUrl: "/imgs/me34.jpg",
    price: 60000,
    currency: "XAF",
    category: "Solar Panel",
  },
  {
    id: "inv-001",
    title: "500W Pure Sine Wave Inverter",
    imageUrl: "/imgs/me34.jpg",
    price: 50000,
    currency: "XAF",
    category: "Inverter",
  },
  {
    id: "inv-002",
    title: "1500W Hybrid Inverter with LCD Display",
    imageUrl: "/imgs/me34.jpg",
    price: 120000,
    currency: "XAF",
    category: "Inverter",
  },
  {
    id: "bat-001",
    title: "12V 100Ah Deep Cycle Battery",
    imageUrl: "/imgs/me34.jpg",
    price: 75000,
    currency: "XAF",
    category: "Battery",
  },
  {
    id: "bat-002",
    title: "12V 200Ah Solar AGM Battery",
    imageUrl: "/imgs/me34.jpg",
    price: 135000,
    currency: "XAF",
    category: "Battery",
  },
  {
    id: "kit-001",
    title: "Complete 300W Solar Kit with Cables",
    imageUrl: "/imgs/me34.jpg",
    price: 150000,
    currency: "XAF",
    category: "Solar Kit",
  },
  {
    id: "kit-002",
    title: "500W Home Solar Power Kit",
    imageUrl: "/imgs/me34.jpg",
    price: 250000,
    currency: "XAF",
    category: "Solar Kit",
  },
  {
    id: "acc-001",
    title: "Solar PV Combiner Box 4 in 1 out",
    imageUrl: "/imgs/me34.jpg",
    price: 30000,
    currency: "XAF",
    category: "Accessory",
  },
  {
    id: "acc-002",
    title: "MC4 Connector Pair",
    imageUrl: "/imgs/me34.jpg",
    price: 4000,
    currency: "XAF",
    category: "Accessory",
  },
  {
    id: "cable-001",
    title: "6mm² Solar Cable 10m",
    imageUrl: "/imgs/me34.jpg",
    price: 7000,
    currency: "XAF",
    category: "Cable",
  },
  {
    id: "cable-002",
    title: "16mm² Battery Cable 5m",
    imageUrl: "/imgs/me34.jpg",
    price: 12000,
    currency: "XAF",
    category: "Cable",
  },
  {
    id: "charge-003",
    title: "MPPT 80A Charge Controller",
    imageUrl: "/imgs/me34.jpg",
    price: 50000,
    currency: "XAF",
    category: "Charge Controller",
  },
  {
    id: "sp-003",
    title: "100W Flexible Solar Panel",
    imageUrl: "/imgs/me34.jpg",
    price: 25000,
    currency: "XAF",
    category: "Solar Panel",
  },
  {
    id: "sp-004",
    title: "300W Monocrystalline Solar Panel",
    imageUrl: "/imgs/me34.jpg",
    price: 90000,
    currency: "XAF",
    category: "Solar Panel",
  },
  {
    id: "inv-003",
    title: "1000W Modified Sine Wave Inverter",
    imageUrl: "/imgs/me34.jpg",
    price: 75000,
    currency: "XAF",
    category: "Inverter",
  },
  {
    id: "inv-004",
    title: "3000W Hybrid Solar Inverter",
    imageUrl: "/imgs/me34.jpg",
    price: 240000,
    currency: "XAF",
    category: "Inverter",
  },
  {
    id: "bat-003",
    title: "24V 100Ah Deep Cycle Battery",
    imageUrl: "/imgs/me34.jpg",
    price: 130000,
    currency: "XAF",
    category: "Battery",
  },
  {
    id: "bat-004",
    title: "24V 200Ah AGM Solar Battery",
    imageUrl: "/imgs/me34.jpg",
    price: 210000,
    currency: "XAF",
    category: "Battery",
  },
  {
    id: "kit-003",
    title: "1000W Complete Solar Kit",
    imageUrl: "/imgs/me34.jpg",
    price: 350000,
    currency: "XAF",
    category: "Solar Kit",
  },
  {
    id: "kit-004",
    title: "2000W Complete Home Solar System",
    imageUrl: "/imgs/me34.jpg",
    price: 560000,
    currency: "XAF",
    category: "Solar Kit",
  },
  {
    id: "acc-003",
    title: "DC Breaker 63A",
    imageUrl: "/imgs/me34.jpg",
    price: 9000,
    currency: "XAF",
    category: "Accessory",
  },
  {
    id: "acc-004",
    title: "12V Solar Light Kit",
    imageUrl: "/imgs/me34.jpg",
    price: 15000,
    currency: "XAF",
    category: "Accessory",
  },
  {
    id: "cable-003",
    title: "25mm² Solar Cable 5m",
    imageUrl: "/imgs/me34.jpg",
    price: 20000,
    currency: "XAF",
    category: "Cable",
  },
  {
    id: "cable-004",
    title: "10mm² Solar PV Cable 10m",
    imageUrl: "/imgs/me34.jpg",
    price: 10000,
    currency: "XAF",
    category: "Cable",
  },
  {
    id: "charge-004",
    title: "60A Solar MPPT Charge Controller with LCD",
    imageUrl: "/imgs/me34.jpg",
    price: 45000,
    currency: "XAF",
    category: "Charge Controller",
  },
  {
    id: "sp-005",
    title: "50W Polycrystalline Solar Panel",
    imageUrl: "/imgs/me34.jpg",
    price: 15000,
    currency: "XAF",
    category: "Solar Panel",
  },
  {
    id: "sp-006",
    title: "400W Monocrystalline Solar Panel",
    imageUrl: "/imgs/me34.jpg",
    price: 120000,
    currency: "XAF",
    category: "Solar Panel",
  },
];

export default ProductsList;
